
from math import log

GENERATOR_NUM_POINTS = 1000
GENERATOR_SIZE_W = 500
GENERATOR_SIZE_H = 500
NUM_LLOYD_ITERATIONS = 3
GENERATOR_ISLAND = False
GENERATOR_LAKE_THRESHOLD = 0.8
GENERATOR_WATER = 0.3
REGIONS_BUISNESS_TRESHHOLD = 0.8
REGIONS_BUISNESS_MAX = int(log(GENERATOR_NUM_POINTS, 3))
if REGIONS_BUISNESS_MAX <= 0:
    REGIONS_BUISNESS_MAX = 1
